Add HttpClientModule & cause a build error
JIT compilation failed for injectable
class c {}
main.js:2:179216
Uncaught Error: The injectable 'c' needs to be compiled using the JIT
compiler, but '@angular/compiler' is not available.

The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT
compilation is used as fallback.

Ideally, the library is processed using the Angular Linker to become
fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using
'@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";'
before bootstrapping.